name: Autoupdate PR
on:
  push:
    branches:
      - main

jobs:
  update_pull_requests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Fetch all branches and tags
        run: git fetch --prune --unshallow

      - name: Auto update pull requests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_LIST=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls?state=open" | jq -r '.[] | .head.ref')
          for pr_branch in $PR_LIST; do
            git checkout "$pr_branch"
            if git merge origin/main; then
              git push
            else
              # Conflict occurred, resolve by keeping our changes
              git checkout --ours .
              git add .
              git commit -m "Auto resolve conflict by keeping our changes"
              git push
            fi
          done
